version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: userServiceDb
    environment:
      - MYSQL_DATABASE=user-service-db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3307:3306'

  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    image: user-service-app
    container_name: userServiceApp
    depends_on:
      - db
      - cache
    build: ./
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://userServiceDb:3306/user-service-db?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.flyway.enabled=true
      - spring.flyway.url=jdbc:mysql://userServiceDb:3306/user-service-db?serverTimezone=UTC
      - spring.flyway.user=root
      - spring.flyway.password=password
      - spring.flyway.group=true
      - spring.application.name=user-service
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
      - spring.redis.host=redis
      - spring.redis.port=6379

networks:
  default:
    name: carsharing
    external: true
